### ISSUE TITLE
Build fails on rwpng.h (#include "png.h")

### ISSUE THREAD

**Issue by mtt87** [imagemin/pngquant-bin#24]
<pre>
✗ pre-build test failed, compiling from source...
✗ Error: Command failed: In file included from pngquant.c:59:
./rwpng.h:35:10: fatal error: 'png.h' file not found
#include "png.h"    /* libpng header; includes zlib.h */
         ^
</pre>

Happening today when trying to install `grunt-contrib-imagemin`, do you have a clue?

Thanks

**Comment by ni3bk** [comment]
Getting same issue on Windows 

e\\pngQ\\pngquant\\target\\release\\build\\pngquant-55a69f10061d96f2\\out\\rwpng.o" "/c" "rwpng.c"
pngquant.c
rwpng.c
rwpng.c(15): fatal error C1083: Cannot open include file: 'png.h': No such file or directory
exit code: 0
exit code: 2

**Comment by ni3bk** [comment]
I could solve above problem, but unable to link lpng, below are the errors i got

_error: linking with `link.exe` failed: exit code: 1120


error: aborting due to previous error

error: Could not compile `pngquant`.

Caused by:
  process didn't exit successfully: `rustc --crate-name pngquant rust/bin.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto --cfg 'feature="default"' --cfg 'feature="imagequant-sys"' --cfg 'feature="lcms2"' --cfg 'feature="lcms2-sys"' --cfg 'feature="sse"' -C metadata=4085dfdaef35af79 -C extra-filename=-4085dfdaef35af79 --out-dir 'C:\Users\nitin.khobragade\pngQ\pngquant\target\release\deps' -L 'dependency=C:\Users\nitin.khobragade\pngQ\pngquant\target\release\deps' --extern 'getopts=C:\Users\nitin.khobragade\pngQ\pngquant\target\release\deps\libgetopts-4a174400976bd2d0.rlib' --extern 'imagequant_sys=C:\Users\nitin.khobragade\pngQ\pngquant\target\release\deps\libimagequant_sys.rlib' --extern 'lcms2_sys=C:\Users\nitin.khobragade\pngQ\pngquant\target\release\deps\liblcms2_sys-1617ce3af664a50e.rlib' --extern 'libc=C:\Users\nitin.khobragade\pngQ\pngquant\target\release\deps\liblibc-b49f3c440d6ef967.rlib' --extern 'libpng_sys=C:\Users\nitin.khobragade\pngQ\pngquant\target\release\deps\liblibpng_sys-dee7b81072565b74.rlib' --extern 'wild=C:\Users\nitin.khobragade\pngQ\pngquant\target\release\deps\libwild-7244012eee2ea441.rlib' -L 'native=C:\Users\nitin.khobragade\pngQ\pngquant\target\release\build\pngquant-55a69f10061d96f2\out' -l static=pngquant -L 'native=C:\Users\nitin.khobragade\pngQ\pngquant\target\release\build\imagequant-sys-b2df9f7d112a9f35\out' -L 'native=C:\Users\nitin.khobragade\pngQ\pngquant\target\release\build\lcms2-sys-5e8cb0308d84e4d8\out' -L 'native=C:\Users\nitin.khobragade\pngQ\pngquant\target\release\build\libz-sys-acb8facb9bb13cf0\out\build'` (exit code: 1)_

**Comment by kornelski** [comment]
@ni3bk it looks like you don't have Visual Studio installed, or you have an incomplete/broken installation of libpng.

**Comment by ni3bk** [comment]
@kornelski I have Visual Studio 17 installed on my machine. I've also compiled libpng12 for 'LIB RELEASE' x64. But still I'm getting the errors, not sure what I'm missing. Below are the logs

error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\nitin.khobragade\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\nitin.khobragade\\pngQ\\pngquant\\target\\release\\deps\\pngquant-4085dfdaef35af79.pngquant.74hvfhzo-cgu.1.rcgu.o" "/OUT:C:\\Users\\nitin.khobragade\\pngQ\\pngquant\\target\\release\\deps\\pngquant-4085dfdaef35af79.exe" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\nitin.khobragade\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\nitin.khobragade\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\nitin.khobragade\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\Users\\nitin.khobragade\\pngQ\\pngquant\\target\\release\\deps" "/LIBPATH:C:\\Users\\nitin.khobragade\\pngQ\\pngquant\\target\\release\\build\\pngquant-55a69f10061d96f2\\out" "/LIBPATH:C:\\Users\\nitin.khobragade\\pngQ\\pngquant\\target\\release\\build\\imagequant-sys-b2df9f7d112a9f35\\out" "/LIBPATH:C:\\Users\\nitin.khobragade\\pngQ\\pngquant\\target\\release\\build\\lcms2-sys-5e8cb0308d84e4d8\\out" "/LIBPATH:C:\\Users\\nitin.khobragade\\pngQ\\pngquant\\target\\release\\build\\libz-sys-acb8facb9bb13cf0\\out\\build" "/LIBPATH:C:\\Users\\nitin.khobragade\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "pngquant.lib" "C:\\Users\\NITIN~1.KHO\\AppData\\Local\\Temp\\rustczqeC2v\\liblcms2_sys-1617ce3af664a50e.rlib" "C:\\Users\\NITIN~1.KHO\\AppData\\Local\\Temp\\rustczqeC2v\\liblibz_sys-6d039f3efbd0bf51.rlib" "C:\\Users\\NITIN~1.KHO\\AppData\\Local\\Temp\\rustczqeC2v\\libimagequant_sys.rlib" "C:\\Users\\nitin.khobragade\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-5fcb08748623a7c4.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: pngquant.lib(rwpng.o) : error LNK2019: unresolved external symbol png_create_read_struct referenced in function rwpng_read_image24_libpng
          pngquant.lib(rwpng.o) : error LNK2019: unresolved external symbol png_create_write_struct referenced in function rwpng_write_image_init
          pngquant.lib(rwpng.o) : error LNK2019: unresolved external symbol png_create_info_struct referenced in function rwpng_read_image24_libpng

**Comment by ni3bk** [comment]
@kornelski I have Visual Studio 17 installed on my machine. I've also compiled libpng12 for 'LIB RELEASE' x64. But still I'm getting the errors, not sure what I'm missing. 
I've kept the zli.lib and libpng.lib at below location "_C:\Users\nitin.khobragade\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib_"
Below are the logs

_error: linking with link.exe failed: exit code: 1120
 |
 = note: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX64\x64\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\Users\nitin.khobragade\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib" "C:\Users\nitin.khobragade\pngQ\pngquant\target\release\deps\pngquant-4085dfdaef35af79.pngquant.74hvfhzo-cgu.1.rcgu.o" "/OUT:C:\Users\nitin.khobragade\pngQ\pngquant\target\release\deps\pngquant-4085dfdaef35af79.exe" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\Users\nitin.khobragade\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\etc\intrinsic.natvis" "/NATVIS:C:\Users\nitin.khobragade\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\etc\liballoc.natvis" "/NATVIS:C:\Users\nitin.khobragade\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\etc\libcore.natvis" "/LIBPATH:C:\Users\nitin.khobragade\pngQ\pngquant\target\release\deps" "/LIBPATH:C:\Users\nitin.khobragade\pngQ\pngquant\target\release\build\pngquant-55a69f10061d96f2\out" "/LIBPATH:C:\Users\nitin.khobragade\pngQ\pngquant\target\release\build\imagequant-sys-b2df9f7d112a9f35\out" "/LIBPATH:C:\Users\nitin.khobragade\pngQ\pngquant\target\release\build\lcms2-sys-5e8cb0308d84e4d8\out" "/LIBPATH:C:\Users\nitin.khobragade\pngQ\pngquant\target\release\build\libz-sys-acb8facb9bb13cf0\out\build" "/LIBPATH:C:\Users\nitin.khobragade\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib" "pngquant.lib" "C:\Users\NITIN1.KHO\AppData\Local\Temp\rustczqeC2v\liblcms2_sys-1617ce3af664a50e.rlib" "C:\Users\NITIN1.KHO\AppData\Local\Temp\rustczqeC2v\liblibz_sys-6d039f3efbd0bf51.rlib" "C:\Users\NITIN~1.KHO\AppData\Local\Temp\rustczqeC2v\libimagequant_sys.rlib" "C:\Users\nitin.khobragade\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib\libcompiler_builtins-5fcb08748623a7c4.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
 = note: pngquant.lib(rwpng.o) : error LNK2019: unresolved external symbol png_create_read_struct referenced in function rwpng_read_image24_libpng
 pngquant.lib(rwpng.o) : error LNK2019: unresolved external symbol png_create_write_struct referenced in function rwpng_write_image_init
 pngquant.lib(rwpng.o) : error LNK2019: unresolved external symbol png_create_info_struct referenced in function rwpng_read_image24_libpng_

**Comment by kornelski** [comment]
Oh, libpng12 is an old buggy garbage. It's 10 years older than the oldest libpng version that I support.

Try:

```sh
cargo clean
set PNG_STATIC=1
cargo build --release
```
